### ISSUE TITLE
Feature List for the static PWA version

### ISSUE THREAD

**Issue by rdmueller** [dukecon/dukecon_pwa#103]
the readme of this project already contains a small feature list.

Let's extend it to make it more marketing like so that people interested in dukecon knwo what it is capable of.

**Comment by sippsack** [comment]
Wenn ich > gradle bakePreview aufrufe, kommt folgender Fehler:

> Task :bakePreview FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':bakePreview'.
> Directory 'C:\03-projects\dukecon\dukecon_webhome\build\docs\html5\site' specified for property 'input' does not exist.
