### ISSUE TITLE
Provide offline functionality for Keycloak login

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#13]
The keycloak tokens should be saved in the settings (local storage) like in the old application.

**Comment by ahus1** [comment]
Added documentation. Works when user is online or offline when the application starts. Offline token is saved in the local storage. 

Functionality will be re-tested once the favorites are added.

**Comment by ahus1** [comment]
as we no longer use the iFrame as it conflicts with offline tokens, I also removed the jquery dependency that was used for dom ready

**Comment by sippsack** [comment]
review done, looks good for me
