### ISSUE TITLE
Save/Load favorites to and from the backend 

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#15]
When logged in, the users favorites should be saved and loaded to/from the backend.

**Comment by ahus1** [comment]
The idea of syncing as implemented here:
  1. get current state from the server
  2. from the server's state remove and add the pending removals and additions (and set this as new client state)
  3. save to server
  4. from the pending removals and additions tick off the ones we memorized in step 2

See Favourites.js for the details.

**Comment by ahus1** [comment]
TODO: tests and docs. Mapping of /preferences URL on latest

**Comment by ahus1** [comment]
@steffchep @sippsack @ascheman - this is now available on latest and works with the new proxy mapping. Ready for review.

**Comment by steffchep** [comment]
Looks good to me!
