### ISSUE TITLE
Use Conference specific CSS dynamically

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#18]

**Comment by ahus1** [comment]
@steffchep @sippsack - this is now ready for review. As the CSS takes a while to load, the first "flash" of the app will be grey, but then it's JavaLand green.

**Comment by sippsack** [comment]
review done, looks good for me. 

@ahus1: but would it also possible to have a static <link rel="stylesheet" href="..."> with an v-if (if conference specific stylesheet exists) instead building a link manually?

**Comment by ahus1** [comment]
The link to the stylesheet should go into the head of the document, [see the docs](https://www.w3schools.com/tags/tag_link.asp)

> This element goes only in the head section, but it can appear any number of times.

Vue.js can only control the areas it has been mounted on (the _<div id="app"></div>_ in the index.html). I already did a trick to get Vis.js running, but I don't think this will work in the header.

On the other hand there seems to be evidence that this works in all browsers when you put it into the body. I made a change to move it to App.vue.

I suppose there is a conference specific stylesheet for all conferences? I don't know about a on/off switch for this...)

@sippsack - Please have a look and comment.

**Comment by ahus1** [comment]
closing due to timeout.
