### ISSUE TITLE
Allow login via Keycloak

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#2]
A user should be able to login via Keycloak

**Comment by ahus1** [comment]
Keycloak needs to be initialized first, as it will use URL redirects that would other wise interfere with the Vue.js router.
The Keycloak client library is wrapped in DuekconKeycloak.js as a singleton for the project.

**Comment by ahus1** [comment]
@sippsack @ascheman @steffchep - ready for review!

**Comment by sippsack** [comment]
looks good for me
