### ISSUE TITLE
Show slides and additional documents for each talk

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_pwa#20]
There should be links to _Presentation_ (Presentation), _Manuscript_ (Manuskript) and _Andere_ (Other).

See https://github.com/dukecon/dukecon_html5/issues/116 und https://redmine.doag.org/issues/4402

**Comment by ahus1** [comment]
Sample from JSON JavaLand 2017

https://latest.dukecon.org/pwa/javaland/2017/rest/conferences/javaland2017

```
      "documents": {
        "slides": "https://www.javaland.eu/formes/pubfiles/8890453/2017-nn-kristian_kottke-ich_bin_dein_nachbar___graphenverarbeitung_mit_apache_flink-praesentation.pdf",
        "manuscript": null,
        "other": null
      }
```

**Comment by ahus1** [comment]
There is now a first preview-version available. Once the user clicks the link, the document opens in a new tab.

This one still needs some love regarding CSS and maybe another layout idea.

https://latest.dukecon.org/pwa/javaland/2017/#/scheduledEvent/529221

![download_example](https://user-images.githubusercontent.com/3957921/33516424-d09a5322-d772-11e7-9bb8-1fdb22dc6cb9.png)

**Comment by ascheman** [comment]
Please beautify the CSS a little more @steffchep

**Comment by steffchep** [comment]
Done, see https://github.com/dukecon/dukecon_pwa/commit/d347909190406b2e17525e1ec377e1d39749ba34 (forgot to add ticket number there)
