### ISSUE TITLE
Load fully-booked and favorites count by eventsBooking URL

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#23]
This URL is more efficient (fewer data) and contains the up-to-date counts of favorites.

**Comment by ahus1** [comment]
Fully booked and favorites count are loaded from the server every 90 minutes. 
@sippsack (or anyone else) This is now ready for review.

**Comment by sippsack** [comment]
commits
188d7168b7929e1c70aeedf6c5c4dd417cb30f61

review finished, looks good for me
