### ISSUE TITLE
Provide search term via URL

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#24]
... and document as provided interface.

**Comment by ahus1** [comment]
@sippsack @steffchep - ready for review.

**Comment by ahus1** [comment]
@sippsack - after you added the feature I noticed the following from a UX perspective: 
* back-navigation works differently: when you type a search string, and you use back navigation, you will un-type letter by letter. Therefor "replace" might be better than "push".
* if you go back to a previous tab (i.e. from speakers to talks) where you have entered a different search term, you'll get the previous search term. This comes as a surprise

From an implementation perspective: 
* Depending on the browser "window.history" might not be available, maybe wrap it with an if.
* the implementation should work without events, as this is component-local. Maybe you could place all you need inside "watch: term"?

**Comment by sippsack** [comment]
@ahus1: I've changed it as you suggested. Please review again.

Search box is kind of global widget, so switching tabs should remember last search term in my opinion. Actually the search box on speaker tab is new behaviour. In the old client we had only a search in the talks tab.

**Comment by ahus1** [comment]
@sippsack - reviewed it, works! Thanks a lot!
