### ISSUE TITLE
Put the version number into the deployed application

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#26]
This will make it easier to find out what version is currently deployed.

**Comment by ahus1** [comment]
The commit ID is now included in the build in a separate file. This allows us to identify the version that is currently deployed (both in test and in production). 

Example: https://latest.dukecon.org/pwa/javaland/2018/COMMITHASH

Docs: https://github.com/dukecon/dukecon_pwa/blob/develop/doc/INTERFACES.adoc#interfaces-for-operations

@sippsack @ascheman @steffchep - ready for review.

**Comment by sippsack** [comment]
review done, looks good for me
