### ISSUE TITLE
Restrict download to participants before and during conference

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#29]
Download before/during conference only for registered participants, after the conference access for all

#20 need to implemented before this feature.

**Comment by ahus1** [comment]
Clarification needed from business point of view: 
* dukecon currently knows only about logged in / not logged in users, but not if the user participates in the particular conference (AFAIK)
* DOAG provides (public) links to the PDFs, currently we publish the PDFs directly to the frontend. Depending on business neeeds we must no longer publish them to the SPA, but must verify access in the backend when accessing the PDF.

**Comment by ascheman** [comment]
@pittorf Can you please check how we can restrict access to the desired participants until conference start? We currently could provide the links only to logged in users (not knowing if they are participants of the conference). Nevertheless we take the links from the public conference data so this is merely security by obscurity. 

Additionally you need to prevent access to the documents from finally access on the PDF publication site until the conference is over.

**Comment by ascheman** [comment]
DOAG will publish documents and links on their own at certain date. It is not in the scope of DukeCon to control access or hide links before publication date.
