### ISSUE TITLE
Update Babel

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#35]
Currently we get a warning during build

```
  [WARNING] npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
```

We should consider updating to `babel-preset-env`.

**Comment by ahus1** [comment]
This is needed for integration of Vis - we can only update this once Vis updates this as well.

**Comment by ahus1** [comment]
... I added section in DEVELOPER.adoc to explain this (see 4ba563da3cd5f6c562269e1fa22310a5bd294bf7)
