### ISSUE TITLE
When searching for "sch" the SPA freezes

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#39]
Happens with: JavaLand 2018. 

Cause: Vue is confused when the layout switches and the keyIds of dom elements are assigned twice (shoul dbe unique)

**Comment by ahus1** [comment]
@ascheman - the fix is available and working on latest.dukecon.org - please deploy to production using the next possible slot. Thanks!

**Comment by ascheman** [comment]
Restarted on Javaland production.
