### ISSUE TITLE
Timetable overview is one-hour-off

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#43]
When using MacOS Safari, iOS Safari, iOS Firefox, the timeline in the timetable view is off. 

Other browsers seem to work.

**Comment by ahus1** [comment]
We now pre-parse the dates before handing them over to VIS visualisation library.

**Comment by ahus1** [comment]
Bug fixed - cc: @ascheman @steffchep @sippsack

**Comment by janwesterkamp** [comment]
Succesfully tested in prod.
