### ISSUE TITLE
Fix "zurück" button

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#46]
_From @michael-simons on March 15, 2018 10:29_

The "Zurück"-Button should work in a consistent way.

When the user has tapped on a talk like in

![img_8b79fee5c1c9-1](https://user-images.githubusercontent.com/526383/37458027-f088d45c-2843-11e8-9b10-bde6c39b8ff4.jpeg)

It navigates back into the talk list

![img_6ac66b5c2cbf-1](https://user-images.githubusercontent.com/526383/37458065-10550b20-2844-11e8-8e07-81c133705f3f.jpeg)

That's fine.

If the user navigates between the days, the user expect that the back button moves back to the previous day. Instead it navigates out of the app back into the homepage or whatever.

_Copied from original issue: dukecon/dukecon#50_

**Comment by ahus1** [comment]
#45 delivers this: when you change the day and then press Back/Zurück this will take you to the previously selected day.

The change is already available on https://latest.dukecon.org/javaland/2018/#/schedule

**Comment by sippsack** [comment]
should we also prevent leaving the app by checking history.back is still
our URL?

Alexander Schwartz <notifications@github.com> schrieb am So., 18. März
2018, 20:06:

**Comment by ahus1** [comment]
@sippsack - you could try. Maybe the button should not be visible at all in this case. But I don't if there is a JavaScript API for this.

On the other hand the user might entered the application by clicking on the program link on the conference page. The last "Zurück/Back" would lead him/her back to the conference page.

**Comment by sippsack** [comment]
yes, there is no javascript api to query the browser history, so this won't
work.
