### ISSUE TITLE
Clarify usage of "Aktiv"-checkbox

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#49]
_From @michael-simons on March 15, 2018 10:14_

The highlighted checkbox in this image

![img_b5ee999a02a6-1](https://user-images.githubusercontent.com/526383/37457249-b4c3e2a6-2841-11e8-90d8-a083a6597049.jpeg)

is irritating. It looks like it is part of the available filter options (like all talks "active") but in fact toggles the configured filtered. As such it should be on the same level as the "Zurücksetzen" button and behave like a toggle button (that is a button that stays in the "pressed" or "active" state).

_Copied from original issue: dukecon/dukecon#48_

**Comment by steffchep** [comment]
Suggestion: Change text to "Filters enabled" / "Filter aktiviert"
