### ISSUE TITLE
Add Image Resource

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#5]
In order to service icons and the conference logo we need to load the images via the existing REST API.

**Comment by ahus1** [comment]
When implementing this feature, I also added functionality to test offline (i.e. while riding on trains). 

This is now ready for review - cc: @sippsack @ascheman @steffchep

**Comment by sippsack** [comment]
review done, looks good for me

**Comment by sippsack** [comment]
review done, looks good for me
