### ISSUE TITLE
Strange characters in talk details

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#50]
_From @annam002 on March 12, 2018 16:16_

In the talk 100% Code Coverage strange characters are shown instead of dashes. Using the Brave Browser on Android.

_Copied from original issue: dukecon/dukecon#46_

**Comment by ascheman** [comment]
_From @annam002 on March 12, 2018 16:17_

![screenshot_20180312-171120](https://user-images.githubusercontent.com/3940199/37295747-3c96f87e-2619-11e8-9ce0-10de55c424f9.png)

**Comment by steffchep** [comment]
Sieht nach einem Datenproblem aus...
