### ISSUE TITLE
Show favorited Talks with an alternating fav-icon on the schedule

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#52]
_From @4223 on February 16, 2018 7:19_

_Copied from original issue: dukecon/dukecon#44_

**Comment by ascheman** [comment]
Who are you, @4223? I prefer to communicate with individuals who publish a "real name" ...

**Comment by ascheman** [comment]
_From @steffchep on February 16, 2018 11:15_

I don't understand the request... what is the purpose here?

**Comment by steffchep** [comment]
No new Input in several months, closing.
