### ISSUE TITLE
transfer favorites to phone

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#57]
_From @kirviq on March 13, 2017 15:3_

It would be nice if you could pick your favorites on a pc, export them to a QR code and import this on a phone. (or transfer in any other way)

_Copied from original issue: dukecon/dukecon_html5#100_

**Comment by ascheman** [comment]
_From @steffchep on March 13, 2017 15:22_

Use case: I do not want to register with the DOAG, or my registration confirmation has not arrived yet.

**Comment by ahus1** [comment]
This would be a nice feature, but so far no-one created a pull request for this feature, and we think that (as a core team) we will don't develop this. We would be happy to re-open this ticket for a pull request.
