### ISSUE TITLE
Don't show spinner for conference with no scheduled talks

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_pwa#58]
Given a conference where no talk have been scheduled yet, a message should appear instead of the infinite spinner.

**Comment by ahus1** [comment]
Initial commit by @sippsack 24aa653c2545b42873f2ac6b46554b8e0c2a2d67

**Comment by ahus1** [comment]
The timetable showed an empty grid. I changed that. I also renamed _loadingFinish_ to _loadingFinished_.

The German translation "Noch keine Vorträge ausgewählt!" sounded like the user needed to do something. Now it's "Talks für diese Konferenz stehen noch nicht fest."

Ready for another review.

**Comment by sippsack** [comment]
@ahus1: thanks for the corrections, looks good for me..

I've added hiding filter box on the left hand side if events list is emtpy:
44bd22fa9715a374272f7117f07089726ba5d38b

Ready for another review.

**Comment by ahus1** [comment]
review done. works for me.
