### ISSUE TITLE
Travis CI build is randomly failing

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_pwa#59]
✖ Testing if element <#talks-grid div.title a> contains text: "100 % Code Coverage - TDD mit Java EE".  - expected "100 % Code Coverage - TDD mit Java EE" but got: "Pipeline as code: Continuous Delivery with Jenkins 2"
    at Object.defaultE2eTests [as default e2e tests] (/home/travis/build/dukecon/dukecon_pwa/test/e2e/specs/test.js:14:15)

100 % Code Coverage - TDD mit Java EE is the first talk of 2018
Pipeline as code: Continuous Delivery with Jenkins 2 is the first talk of 2017

I'm not sure, why the e2e tests sometimes call JavaLand 2018 and sometimes 2017. Webpack conf contains a proxy to JavaLand 2018 latest.

@ahus1: any ideas?

**Comment by ahus1** [comment]
There is a mechanism that when you are using a localhost (development) version it will switch to the static data when the remote service is not available. This makes it easy for development. 

The static data is 2017, the data on latest.dukecon.org is 2018.

I suppose this triggers also on TravisCI if latest.dukecon.org is unavailable when travis runs. 

So, that's the reason. How to fix it? I think we should keep an end-to-end test. Maybe the Jenkins build is restarting the containers the moment travis is running the e2e tests? 

It would help if Jenkins would - on a frontend build - only restart the frontend container and not the backend container as well.

**Comment by sippsack** [comment]
simple solution: use same conference data for fallback and usual data from latest server (e. g. from 2018)

more complex solution: @ascheman can we optimize restart behaviour of latest docker images so that always a latest images is running when the tests are running

**Comment by ascheman** [comment]
I have switched off Travis builds (on https://travis-ci.org/github/dukecon/dukecon_pwa/settings) since we hardly ever use Travis regularly. Additionally we should go for Docker based builds, cf. #37.
