### ISSUE TITLE
When opening the app with only english content, I had all labels empty because probably the default was german

### ISSUE THREAD

**Issue by chrisdutz** [dukecon/dukecon_pwa#62]
In case of the ApacheCon, English is the only language. When I started the site for the first time, it seems german was selected, which didn't exist. So all labels were simply blank. I had to switch to English first to see something. 

Would be cool if the algorithm would be the following:
- No language Selected
  - Check if the browsers default language exists
    - If it exists, select that
    - if it doesn't select the default language for the conference
- Language Selected
  - Check if this exists
    - If it exists, select that
    - if it doesn't select the default language for the conference

**Comment by ahus1** [comment]
As part of #63 I've implemented: when all of the talks are in one language, the UI is also switched to that language and the language button is hidden. I think this works good enough to close this ticket as well.
