### ISSUE TITLE
Make it possible to disable the language toggle

### ISSUE THREAD

**Issue by chrisdutz** [dukecon/dukecon_pwa#63]
Currently the application expects EN and DE to always exist, this is not the case, it would be good if (if for example its an only English conference) to disable the language toggle functionality.

**Comment by ahus1** [comment]
@chrisdutz - this is now ready for review. As the change has been done on the develop branch, you'll probably need to rebase your development branch.

**Comment by ahus1** [comment]
waiting for review for one month. closing due to timeout.
