### ISSUE TITLE
Speaker infos overlays feedback modal dialogue

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_pwa#67]
![image](https://user-images.githubusercontent.com/413426/39087595-7b17f004-45a3-11e8-8033-f12f32f7d4a8.png)
reproduce: https://latest.dukecon.org/apex/2018/#/scheduledEvent/553514
log in
click on feedback

**Comment by ahus1** [comment]
@steffchep provided the code snipped, review on latest ok.
