### ISSUE TITLE
Typo in "Favorite"/"Favourite"

### ISSUE THREAD

**Issue by chrisdutz** [dukecon/dukecon_pwa#68]
It seems to be a typo in the text resources.
If a talk is not a favourite, it says: "Save as favorite" and as soon as that's done it says "Favourite saved" ... I think we should stick to "Favourite".

Unfortunately I haven't gotten through to UI coding ... and I don't know how I would get this online for ApacheCon. I don't just want to do a full text search and change every usage of "favorite" as there are several.

**Comment by ahus1** [comment]
Grammarist says (http://grammarist.com/spelling/favorite-favourite/): Favorite and favourite are different spellings of the same word. Favorite is the preferred spelling in the U.S., while favourite is preferred in all the other main varieties of English. These preferences extend to all derivatives, including favorites/favourites, favoritism/favouritism, and favorited/favourited.

**Comment by ahus1** [comment]
fixed in translation file.
