### ISSUE TITLE
Unknown user changes participant count in UI

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#73]
When a user is not logged in and clicks a _star_ to set or reset a favorite talk, the count of used seats is incremented/decremented and may be different from the value stored in the backend.
If the user is not logged in, his click actions should not update the (local) count.

**Comment by steffchep** [comment]
if a lot of users are not logged in, this means that a lot of favorites, and therefore potential visitors, are not factored into the room planning. Are we sure this is what we want?

**Comment by ascheman** [comment]
No, favorites are only stored centrally for logged in users. If you are not logged in, the talk preference is only stored locally but can never be synchronized (and counted) on the central server. So if people do not log in, we can never estimate the number of participants to a talk.

**Comment by steffchep** [comment]
This means that our entire room planning is completely worthless unless we force people to log in. 
I know around 10 People personally who would stop using the planner if we did that :/

**Comment by steffchep** [comment]
Please test this some more - I think it works as we want now, but not sure

**Comment by steffchep** [comment]
Tested by @sippsack
