### ISSUE TITLE
Return from Abstract returns ever to first conference day.

### ISSUE THREAD

**Issue by tkleiber** [dukecon/dukecon_pwa#76]
It should return to the page for the day, where I select the abstract.

**Comment by sippsack** [comment]
we will have a look for further releases

**Comment by steffchep** [comment]
@tkleiber looking into this - workaround is to use the browser-back button instead, that will return you to the previously selected day

**Comment by steffchep** [comment]
Scroll issue seems to have been browser related (Brave) -  closing
