### ISSUE TITLE
Add Talk Grid to Schedule

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_pwa#8]

**Comment by ahus1** [comment]
@sippsack I see you implemented this as part of Conference.js - this might only be needed by the component creating the overview, therefore you can place it in the javascript block of the component (probably as a computed element). But let's wait and see what the component will look like.

**Comment by ahus1** [comment]
Done: first implementation of talk grid. 

Todo: update docs, add test cases, check performance

optional/enhancement: use separate routes for each day

**Comment by ahus1** [comment]
Updated docs. Test case already part of Schedule test. Ready for review.
