### ISSUE TITLE
Provide feedback always visible for admins also when event is not yet started or already expired

### ISSUE THREAD

**Issue by sippsack** [dukecon/dukecon_pwa#80]

**Comment by ascheman** [comment]
??? Please provide a short explanation, @sippsack

**Comment by sippsack** [comment]
At DOAG conference all were thinking that feedback function is already active but it wasn't. Feedback button is only visible if the talk has started. So it can't be checked if the functionality is activated at all. As admin it should always possible to give (test) feedback, also for events not yet started or already finished.

**Comment by steffchep** [comment]
How exactly should that look? Where should the test feedback go? If it goes to a speaker via the regular feedback widget, how will it be filtered out? 

Wouldn't it be better to add a status "Feedback enabled for this conference" in the admin app, and perhaps a "Test" button that sends a standardized request to some fixed user? That way it is easy to identify when the feedback is processed.

**Comment by sippsack** [comment]
Test feedback goes to feedback server as normal ones. We just can write "testing" for the comment and choose a non relevant event (welcome keynote).
That would make it possible to test the real functionality before a conference starts especially if it still needs to be activated or when the routing in the edge service is not working.

**Comment by steffchep** [comment]
I'm just worried that we don't have the control over what gets entered if we allow a regular feedback - hence my suggestion of a "Test" button that just sends this request regarding a configurable event ID, maybe?
