### ISSUE TITLE
Show audience level on talks view and details view

### ISSUE THREAD

**Issue by albers** [dukecon/dukecon_pwa#86]
One important piece of information when planning a JavaLand visit is the audience level: beginner, advanced, expert.
The only way to get this information is to apply the corresponding filters and watch the talks appearing and disappearing.

It would be very helpful to have this information on the talk's details page and the overview.

**Comment by sippsack** [comment]
Thanks for your idea. We already have this information (audienceId in each talk). The levels are dynamic and at JavaLand it is Beginner, Expert, Advanced. We need nice icons and a kind of tooltip/help (tooltip makes sense on desktop only)

**Comment by albers** [comment]
closing this issue because it went stale.
