### ISSUE TITLE
Login not possible/flaky

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_pwa#89]
Currently a login to DukeCon seems to be impossible (at least on latest/testing) or sometimes it is not completing to retrieve a new token.
Unfortunately this (mis-) behaviour seems to be unstable.

@srose has already investigated the problem?

**Comment by ascheman** [comment]
Was this problem solved by 477136dd42f077768b5d35942e40145b1dbedf79, @ahus1?

**Comment by ahus1** [comment]
@ascheman - what does 'currently' mean? I made my commit some time ago. The change is available at least on latest. Latest ist working for me. What browser, what platform (mobile/desktop)?

**Comment by ascheman** [comment]
As of today I do not seem to have any problems anymore.
